### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by codebynumbers** [codebynumbers/ftpretty#9]

**Comment by bivald** [comment]
An example branch of Python 3 support can be found on https://github.com/enplore/ftpretty/ 

I don't want to create a pull request because I haven't tested it enough yet (we rely on it heavily internally though and it works well, no issues). Also, I haven't tested to make sure it still supports Python 2 (although it should, at least 2.7.X)

**Comment by codebynumbers** [comment]
I saw that and started checking it. I haven't used python 3 myself, but should be able to get something working with Travis. I'd like it if you made a PR anyway and we can work to get it tested and merged.
